name: 1-1 Mona Start

on:
  workflow_call:
    inputs:
      issue-number:
        description: "The issue number to show the challenge description"
        required: true
        type: number

jobs:
  show_challenge:
    name: Show Challenge
    runs-on: ubuntu-latest
    env:
      REPO_IMAGE_BASE_URL: ${{ github.server_url }}/${{ github.repository }}/raw/${{ github.event.repository.default_branch }}/.github/images
    steps:
      - uses: actions/checkout@v5

      - name: Build comment - show challenge intro
        id: build-challenge-intro
        uses: ./.github/actions/render-markdown-template
        with:
          template-file: .github/steps/1-1-mona-intro.md
          repo-image-base-url: ${{ env.REPO_IMAGE_BASE_URL }}

      - name: Add comment - show challenge intro
        uses: GrantBirki/comment@v2.1.1
        with:
          issue-number: ${{ inputs['issue-number'] }}
          body: ${{ steps.build-challenge-intro.outputs.rendered-text }}

      - name: Build comment - show task
        id: build-task
        uses: ./.github/actions/render-markdown-template
        with:
          template-file: .github/steps/1-2-mona-talk.md
          repo-image-base-url: ${{ env.REPO_IMAGE_BASE_URL }}

      - name: Add comment - show task
        uses: GrantBirki/comment@v2.1.1
        with:
          issue-number: ${{ inputs['issue-number'] }}
          body: ${{ steps.build-task.outputs.rendered-text }}

      - name: Build comment - show graph
        id: build-graph
        uses: ./.github/actions/render-markdown-template
        with:
          template-file: .github/steps/1-3-mona-graph.md
          repo-image-base-url: ${{ env.REPO_IMAGE_BASE_URL }}

      - name: Add comment - show graph
        uses: GrantBirki/comment@v2.1.1
        with:
          issue-number: ${{ inputs['issue-number'] }}
          body: ${{ steps.build-graph.outputs.rendered-text }}

      - name: Disable current workflow and enable next workflow
        run: |
          gh workflow disable "1-1 Mona Start" || true
          gh workflow enable "1-2 Mona Check" || true
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
