name: 3-1 Ducky Start

on:
  workflow_call:
    inputs:
      issue-number:
        description: "The issue number to show the challenge description"
        required: true
        type: number

jobs:
  show_challenge:
    name: Show Challenge
    runs-on: ubuntu-latest
    env:
      REPO_IMAGE_BASE_URL: ${{ github.server_url }}/${{ github.repository }}/raw/${{ github.event.repository.default_branch }}/.github/images

    steps:
      - uses: actions/checkout@v5

      - name: Build comment - show file content
        id: build-intro
        uses: ./.github/actions/render-markdown-template
        with:
          template-file: .github/steps/3-1-ducky-intro.md
          repo-image-base-url: ${{ env.REPO_IMAGE_BASE_URL }}

      - name: Add comment - show file content
        uses: GrantBirki/comment@v2.1.1
        with:
          issue-number: ${{ inputs['issue-number'] }}
          body: ${{ steps.build-intro.outputs.rendered-text }}

      - name: Build comment - show task
        id: build-task
        uses: ./.github/actions/render-markdown-template
        with:
          template-file: .github/steps/3-2-ducky-talk.md
          template-vars: |
            repo_image_base_url: ${{ env.REPO_IMAGE_BASE_URL }}
          repo-image-base-url: ${{ env.REPO_IMAGE_BASE_URL }}

      - name: Add comment - show task
        uses: GrantBirki/comment@v2.1.1
        with:
          issue-number: ${{ inputs['issue-number'] }}
          body: ${{ steps.build-task.outputs.rendered-text }}

      - name: Disable current workflow and enable next workflow
        run: |
          gh workflow disable "3-1 Ducky Start" || true
          gh workflow enable "3-2 Ducky Check" || true
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
